### ISSUE TITLE
URLs should be autolinked

### ISSUE THREAD

**Issue by anandology** [pythonindia/junction#547] opened 2017-09-23 14:59 UTC
The markdown format expects urls to be put between `<` and `>` to make them links.  I see lot of speakers adding links to their slides, but the are not hyperlinked. 

Both GitHub and StackOverflow uses a modified version of markdown that autolinks URLs. Junction too should support this extension.

References:

* [GitHub Flavored Markdown](https://github.github.com/gfm/)

**Comment by anandology** [comment] 2017-09-23 15:13
Here is a sample code that you may be able to adopt for this:

https://github.com/internetarchive/openlibrary/blob/cc3a6ea65081e466866d1908cd54c5cd77ce4fcc/openlibrary/core/olmarkdown.py#L23

**Comment by kracekumar** [comment] 2017-11-03 05:47
Duplicate of #539.

**Comment by anujaagarwal** [comment] 2019-08-02 14:04
Hello @anandology , @kracekumar  I want to work on this issue, please can you explain precisely what to do?!

**Comment by ananyo2012** [comment] 2020-03-16 18:05
Closing this as this is duplicate of #539

**Closed by ananyo2012** 2020-03-16 18:05 UTC
Labels: Enhancement
