### ISSUE TITLE
Change submissions closing based on Proposal Types.

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/junction#172] opened 2015-03-03 03:50 UTC
We presently close submissions based on conference.
For PyCon India we will start with Workshop and Talks as proposal types as we near the conference dates we will have open space, Dev sprints and lighting talk proposal type to be opened.
Open space/lighting talk might not be reviewed but will help in tracking thing better.

**Comment by theskumar** [comment] 2016-03-31 20:16
This looks duplicate of #291, @kracekumar it seems this functionality exist now. Please confirm if not. Thanks.

**Comment by kracekumar** [comment] 2016-04-04 21:08
Yep this is fixed.

On Fri, Apr 1, 2016 at 1:46 AM, Saurabh Kumar <notifications@github.com>
wrote:

> This looks duplicate of #291
> <https://github.com/pythonindia/junction/issues/291>, @kracekumar
> <https://github.com/kracekumar> it seems this functionality exist now.
> Please confirm if not. Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonindia/junction/issues/172#issuecomment-204107177>
>



-- 
Regards
Kracekumar Ramaraj
http://kracekumar.com

**Closed** 2016-04-04 23:45 UTC
Labels: Enhancement
