### ISSUE TITLE
A module to send broadcast emails to people who proposed

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/junction#551] opened 2017-10-14 17:14 UTC
A module with some kind of broadcast mechanism is needed to send broadcast emails to people who have proposed a talk or a workshop. This is much needed to easily get back to people with respect to confirmation or details about then if they are speaking.

**Comment by kracekumar** [comment] 2017-11-03 06:32
Duplicate of https://github.com/pythonindia/junction/issues/510

**Closed by kracekumar** 2017-11-03 06:32 UTC
Labels: Feature
